# Generated by Django 4.2 on 2024-02-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead_app', '0001_initial'),
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_app.contract')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_app.lead')),
            ],
        ),
    ]
